module.exports = {
  alerting: 
  [
    'sre/alerting/alerting-strategy',
  ],
  angular: 
  [
    'dev/angular/angularjs-overview',
  ],
  ansible: 
  {

  },
  availability: 
  [
    'sre/availability/meaningful-availability',
  ],
  docker: 
  {

  },
  elastic: 
  {

  },
  git: 
  {

  },
  incidentresponse:
  [
    'sre/incident-response/incident-command-system',
    'sre/incident-response/postmortems',
  ],
  java: 
  [
    'dev/java/java-overview',
    'dev/java/java-syntax',
  ],
  javascript: 
  [
    {
      JavaScript:
      [
      'dev/javascript/javascript-overview',
      'dev/javascript/javascript-keywords',
      'dev/javascript/javascript-syntax',
      'dev/javascript/javascript-datatypes',
      'dev/javascript/javascript-control-structures',
      ],
    },
    {
        "Node.js":
        [
        'dev/javascript/node.js/node.js-overview',
        ],
      },
  ],
  jaeger: 
  {

  },
  kubernetes: 
  [
    'infrastructure/containerization/kubernetes/kubernetes-overview',
    {
      kubectl:
      [
        'infrastructure/containerization/kubernetes/kubectl/kubectl-overview',
        'infrastructure/containerization/kubernetes/kubectl/installing-kubectl',
      ],
    },
  ],
  monitor: 
  [
    'sre/monitoring/monitoring-pattern',
    'sre/monitoring/the-four-golden-signals',
    'sre/monitoring/monitoring-glossary',
  ],
  networking: 
  [
    'infrastructure/networking/networking-overview',
    {
      OSI:
      [
        'infrastructure/networking/osi-model',
      ],
      gRPC:
      [
        'infrastructure/networking/grpc',
      ]
    },
  ],
  python: 
  [
    'dev/python/python-overview',
    'dev/python/python-keywords',
    'dev/python/python-syntax',
    'dev/python/python-datatypes',
    'dev/python/python-control-structures',
    'dev/python/python-useful-methods',
    'dev/python/python-debugging',
    'dev/python/changing-python-versions',
  ],
  reliability:
  [
    'sre/reliability/reliability-roadmap',
    'sre/reliability/chaos-engineering'
  ],
  ruby: 
  [
    'dev/ruby/ruby-overview',
    'dev/ruby/ruby-keywords',
    'dev/ruby/ruby-syntax',
    'dev/ruby/ruby-datatypes',
    'dev/ruby/ruby-control-structures',
    'dev/ruby/ruby-useful-methods',
  ],
  sre:
  [
    'sre/sre',
    'sre/new-relic-sre',
    'sre/be-a-better-sre'
  ],
  techbooks: 
  {
    Google:
    [
      'books/tech-books/google-site-reliability-engineering',
    ],
    DevOps:
    [
      'books/tech-books/phoenix-project',
    ],
  },
  healthcarebooks: 
  [
    'books/healthcare-books/an-american-sickness',
  ],
  businessbooks: 
  [
    'books/business-books/the-checklist-manifesto',
    'books/business-books/you-win-in-the-locker-room-first',
    'books/business-books/deep-diversity',
  ],
};
